//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.29;Initial Catalog=CourierDetails;Persist Security Info=Tru" +
            "e;User ID=sa;Password=sreenath")]
        public string CourierDetailsConnectionString {
            get {
                return ((string)(this["CourierDetailsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=213.42.60.233;Initial Catalog=CourierDetails;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=Sreenath@123;Connect Timeout=900")]
        public string webstring {
            get {
                return ((string)(this["webstring"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=APPSATRACODB2\\APPDBSERVER;Initial Catalog=CourierDetails;Persist Secu" +
            "rity Info=True;User ID=sa;Password=sreenath;Connect Timeout=900")]
        public string teststring {
            get {
                return ((string)(this["teststring"]));
            }
            set {
                this["teststring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\it-dept\\Project\\SHIPITTEST\\")]
        public string Officelog {
            get {
                return ((string)(this["Officelog"]));
            }
            set {
                this["Officelog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\213.42.33.230 \\Project\\SHIPITTEST\\")]
        public string Remotelog {
            get {
                return ((string)(this["Remotelog"]));
            }
            set {
                this["Remotelog"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.4;Initial Catalog=Art;Persist Security Info=True;User ID=sa" +
            ";Password=Sreenath@123")]
        public string ArtConnectionString {
            get {
                return ((string)(this["ArtConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=213.42.60.233;Initial Catalog=Art;Persist Security Info=True;User ID=" +
            "sa;Password=Sreenath@123")]
        public string WebARTConnectionString {
            get {
                return ((string)(this["WebARTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.250;Initial Catalog=DB_Orgin;Persist Security Info=True;Use" +
            "r ID=sa;Password=admin_123")]
        public string OrginconnectionString {
            get {
                return ((string)(this["OrginconnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=197.232.31.250; Initial Catalog=DB_Orgin;Persist Security Info=True;U" +
            "ser ID=sa;Password=admin_123")]
        public string WebOrginconnectionString {
            get {
                return ((string)(this["WebOrginconnectionString"]));
            }
            set {
                this["WebOrginconnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ATRACO-SVR-003\\HONEWSERVER;Initial Catalog=Art;User ID=sa;Password=Sr" +
            "eenath@123")]
        public string ArtConnectionString1 {
            get {
                return ((string)(this["ArtConnectionString1"]));
            }
        }
    }
}
