//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtEntities : DbContext
    {
        public ArtEntities()
            : base("name=ArtEntities")
        {
        }
        public ArtEntities(string sConnectionString)
            : base("name=ArtEntitiesWeb")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltUOMMaster> AltUOMMasters { get; set; }
        public virtual DbSet<AtcDetail> AtcDetails { get; set; }
        public virtual DbSet<AtcMaster> AtcMasters { get; set; }
        public virtual DbSet<AtcRawMaterialMaster> AtcRawMaterialMasters { get; set; }
        public virtual DbSet<BankMaster> BankMasters { get; set; }
        public virtual DbSet<BuyerDestinationMaster> BuyerDestinationMasters { get; set; }
        public virtual DbSet<BuyerMaster> BuyerMasters { get; set; }
        public virtual DbSet<BuyerPOMaster> BuyerPOMasters { get; set; }
        public virtual DbSet<BuyerStyleMaster> BuyerStyleMasters { get; set; }
        public virtual DbSet<CalculationModeMaster> CalculationModeMasters { get; set; }
        public virtual DbSet<ChannelMaster> ChannelMasters { get; set; }
        public virtual DbSet<ColorMaster> ColorMasters { get; set; }
        public virtual DbSet<CostingComponentMaster> CostingComponentMasters { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<CourierEntry> CourierEntries { get; set; }
        public virtual DbSet<CurrencyMaster> CurrencyMasters { get; set; }
        public virtual DbSet<CutOrderDO> CutOrderDOes { get; set; }
        public virtual DbSet<CutOrderMaster> CutOrderMasters { get; set; }
        public virtual DbSet<CuttingDetail> CuttingDetails { get; set; }
        public virtual DbSet<DeliveryMethodMaster> DeliveryMethodMasters { get; set; }
        public virtual DbSet<DeliveryOrderDetail> DeliveryOrderDetails { get; set; }
        public virtual DbSet<DeliveryOrderMaster> DeliveryOrderMasters { get; set; }
        public virtual DbSet<DeliveryOrderStockDetail> DeliveryOrderStockDetails { get; set; }
        public virtual DbSet<DeliveryOrderStockMaster> DeliveryOrderStockMasters { get; set; }
        public virtual DbSet<DeliveryReceiptDetail> DeliveryReceiptDetails { get; set; }
        public virtual DbSet<DeliveryReceiptMaster> DeliveryReceiptMasters { get; set; }
        public virtual DbSet<DeliveryReceiptStockDetail> DeliveryReceiptStockDetails { get; set; }
        public virtual DbSet<DeliveryStockReceiptMaster> DeliveryStockReceiptMasters { get; set; }
        public virtual DbSet<DeliveryTermMaster> DeliveryTermMasters { get; set; }
        public virtual DbSet<DocDetail> DocDetails { get; set; }
        public virtual DbSet<DocMaster> DocMasters { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<EtaDate> EtaDates { get; set; }
        public virtual DbSet<ExtraRequestReasonMaster> ExtraRequestReasonMasters { get; set; }
        public virtual DbSet<FabricRollmaster> FabricRollmasters { get; set; }
        public virtual DbSet<FactoryType> FactoryTypes { get; set; }
        public virtual DbSet<FactWareLinkMaster> FactWareLinkMasters { get; set; }
        public virtual DbSet<GarmentCategory> GarmentCategories { get; set; }
        public virtual DbSet<GoodsInTransit> GoodsInTransits { get; set; }
        public virtual DbSet<InventoryLoanMaster> InventoryLoanMasters { get; set; }
        public virtual DbSet<InventoryMaster> InventoryMasters { get; set; }
        public virtual DbSet<InventoryMissingDetail> InventoryMissingDetails { get; set; }
        public virtual DbSet<InventoryMissingRequest> InventoryMissingRequests { get; set; }
        public virtual DbSet<InventoryStockTransferDetail> InventoryStockTransferDetails { get; set; }
        public virtual DbSet<InventoryStockTransferMaster> InventoryStockTransferMasters { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual DbSet<ItemGroupMaster> ItemGroupMasters { get; set; }
        public virtual DbSet<JobContractDetail> JobContractDetails { get; set; }
        public virtual DbSet<JobContractMaster> JobContractMasters { get; set; }
        public virtual DbSet<JobContractOptionalDetail> JobContractOptionalDetails { get; set; }
        public virtual DbSet<JobContractOptionalMaster> JobContractOptionalMasters { get; set; }
        public virtual DbSet<LCBankAdviceDetail> LCBankAdviceDetails { get; set; }
        public virtual DbSet<LCDetail> LCDetails { get; set; }
        public virtual DbSet<LCMaster> LCMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<MerchandiserMaster> MerchandiserMasters { get; set; }
        public virtual DbSet<MrnDetail> MrnDetails { get; set; }
        public virtual DbSet<MrnMaster> MrnMasters { get; set; }
        public virtual DbSet<PaymentModeMaster> PaymentModeMasters { get; set; }
        public virtual DbSet<PaymentTermMaster> PaymentTermMasters { get; set; }
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<POApproval> POApprovals { get; set; }
        public virtual DbSet<POCurrExRate> POCurrExRates { get; set; }
        public virtual DbSet<POPackDetail> POPackDetails { get; set; }
        public virtual DbSet<PoPackMaster> PoPackMasters { get; set; }
        public virtual DbSet<ProcurementDetail> ProcurementDetails { get; set; }
        public virtual DbSet<ProcurementMaster> ProcurementMasters { get; set; }
        public virtual DbSet<ProductionReportDetail> ProductionReportDetails { get; set; }
        public virtual DbSet<RecieptMaster> RecieptMasters { get; set; }
        public virtual DbSet<RequestOrderDetail> RequestOrderDetails { get; set; }
        public virtual DbSet<RequestOrderMaster> RequestOrderMasters { get; set; }
        public virtual DbSet<RequestOrderStockDetail> RequestOrderStockDetails { get; set; }
        public virtual DbSet<RequestOrderStockMaster> RequestOrderStockMasters { get; set; }
        public virtual DbSet<RoInDetail> RoInDetails { get; set; }
        public virtual DbSet<ROINMaster> ROINMasters { get; set; }
        public virtual DbSet<RollInventoryMaster> RollInventoryMasters { get; set; }
        public virtual DbSet<SeasonMaster> SeasonMasters { get; set; }
        public virtual DbSet<SeasonType> SeasonTypes { get; set; }
        public virtual DbSet<ServicePOMaster> ServicePOMasters { get; set; }
        public virtual DbSet<ServiceTypeMaster> ServiceTypeMasters { get; set; }
        public virtual DbSet<ShipmentHandOverDetail> ShipmentHandOverDetails { get; set; }
        public virtual DbSet<ShipmentHandOverMaster> ShipmentHandOverMasters { get; set; }
        public virtual DbSet<SizeMaster> SizeMasters { get; set; }
        public virtual DbSet<SkuRawmaterialDetail> SkuRawmaterialDetails { get; set; }
        public virtual DbSet<SkuRawMaterialMaster> SkuRawMaterialMasters { get; set; }
        public virtual DbSet<StockGoodsInTransit> StockGoodsInTransits { get; set; }
        public virtual DbSet<StockInventoryMaster> StockInventoryMasters { get; set; }
        public virtual DbSet<StockMRNDetail> StockMRNDetails { get; set; }
        public virtual DbSet<StockMrnMaster> StockMrnMasters { get; set; }
        public virtual DbSet<StockPODetail> StockPODetails { get; set; }
        public virtual DbSet<StockPOMaster> StockPOMasters { get; set; }
        public virtual DbSet<StockRecieptMaster> StockRecieptMasters { get; set; }
        public virtual DbSet<StyleColor> StyleColors { get; set; }
        public virtual DbSet<StyleCostingComponentDetail> StyleCostingComponentDetails { get; set; }
        public virtual DbSet<StyleCostingDetail> StyleCostingDetails { get; set; }
        public virtual DbSet<StyleCostingMaster> StyleCostingMasters { get; set; }
        public virtual DbSet<StyleSize> StyleSizes { get; set; }
        public virtual DbSet<SupplierDocumentMaster> SupplierDocumentMasters { get; set; }
        public virtual DbSet<SupplierInvoiceDetail> SupplierInvoiceDetails { get; set; }
        public virtual DbSet<SupplierInvoiceMaster> SupplierInvoiceMasters { get; set; }
        public virtual DbSet<SupplierMaster> SupplierMasters { get; set; }
        public virtual DbSet<SupplierStockInvoiceDetail> SupplierStockInvoiceDetails { get; set; }
        public virtual DbSet<SupplierStockInvoiceMaster> SupplierStockInvoiceMasters { get; set; }
        public virtual DbSet<SupplierUserMaster> SupplierUserMasters { get; set; }
        public virtual DbSet<SupportTicket> SupportTickets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Template_Master> Template_Master { get; set; }
        public virtual DbSet<TemplateColor> TemplateColors { get; set; }
        public virtual DbSet<TemplateComposition> TemplateCompositions { get; set; }
        public virtual DbSet<TemplateConstruction> TemplateConstructions { get; set; }
        public virtual DbSet<TemplateSize> TemplateSizes { get; set; }
        public virtual DbSet<TemplateWeight> TemplateWeights { get; set; }
        public virtual DbSet<TemplateWidth> TemplateWidths { get; set; }
        public virtual DbSet<TransferToGstockDetail> TransferToGstockDetails { get; set; }
        public virtual DbSet<TransferToGstockMaster> TransferToGstockMasters { get; set; }
        public virtual DbSet<UOMMaster> UOMMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
