//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtcDetail
    {
        public AtcDetail()
        {
            this.CutOrderMasters = new HashSet<CutOrderMaster>();
            this.JobContractDetails = new HashSet<JobContractDetail>();
            this.JobContractOptionalDetails = new HashSet<JobContractOptionalDetail>();
            this.POPackDetails = new HashSet<POPackDetail>();
            this.StyleCostingMasters = new HashSet<StyleCostingMaster>();
        }
    
        public decimal OurStyleID { get; set; }
        public decimal AtcId { get; set; }
        public string OurStyle { get; set; }
        public string BuyerStyle { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> FOB { get; set; }
        public Nullable<decimal> CategoryID { get; set; }
    
        public virtual AtcMaster AtcMaster { get; set; }
        public virtual ICollection<CutOrderMaster> CutOrderMasters { get; set; }
        public virtual ICollection<JobContractDetail> JobContractDetails { get; set; }
        public virtual ICollection<JobContractOptionalDetail> JobContractOptionalDetails { get; set; }
        public virtual ICollection<POPackDetail> POPackDetails { get; set; }
        public virtual ICollection<StyleCostingMaster> StyleCostingMasters { get; set; }
    }
}
