//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtcRawMaterialMaster
    {
        public AtcRawMaterialMaster()
        {
            this.SkuRawMaterialMasters = new HashSet<SkuRawMaterialMaster>();
        }
    
        public decimal AtcRaw_PK { get; set; }
        public Nullable<decimal> Template_PK { get; set; }
        public Nullable<decimal> Atc_id { get; set; }
        public string TempCode { get; set; }
        public string TemplateName { get; set; }
        public Nullable<decimal> TemplateCount { get; set; }
    
        public virtual AtcMaster AtcMaster { get; set; }
        public virtual Template_Master Template_Master { get; set; }
        public virtual ICollection<SkuRawMaterialMaster> SkuRawMaterialMasters { get; set; }
    }
}
