//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMaster
    {
        public BankMaster()
        {
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
            this.LCMasters = new HashSet<LCMaster>();
        }
    
        public decimal Bank_PK { get; set; }
        public string BankName { get; set; }
    
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual ICollection<LCMaster> LCMasters { get; set; }
    }
}
