//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerDestinationMaster
    {
        public BuyerDestinationMaster()
        {
            this.PoPackMasters = new HashSet<PoPackMaster>();
        }
    
        public decimal BuyerDestination_PK { get; set; }
        public string BuyerDestination { get; set; }
        public Nullable<decimal> BuyerID { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual ICollection<PoPackMaster> PoPackMasters { get; set; }
    }
}
