//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelMaster
    {
        public ChannelMaster()
        {
            this.PoPackMasters = new HashSet<PoPackMaster>();
        }
    
        public decimal ChannelID { get; set; }
        public string ChannelName { get; set; }
    
        public virtual ICollection<PoPackMaster> PoPackMasters { get; set; }
    }
}
