//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostingComponentMaster
    {
        public CostingComponentMaster()
        {
            this.StyleCostingComponentDetails = new HashSet<StyleCostingComponentDetail>();
        }
    
        public decimal CostComp_PK { get; set; }
        public string ComponentName { get; set; }
        public string IsOptional { get; set; }
        public string CalculationType { get; set; }
    
        public virtual ICollection<StyleCostingComponentDetail> StyleCostingComponentDetails { get; set; }
    }
}
