//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierEntry
    {
        public decimal CourierEntry_PK { get; set; }
        public Nullable<System.DateTime> CourierDate { get; set; }
        public string CourierContent { get; set; }
        public string Buyer { get; set; }
        public string AtcorStyle { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Destination { get; set; }
        public string IsAtracoAccount { get; set; }
        public string IsNormalAccount { get; set; }
        public string IsNorrmalCourier { get; set; }
        public Nullable<double> WeightofCourier { get; set; }
        public Nullable<double> ApproximateCost { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public string AccountNumber { get; set; }
        public string CourierProvider { get; set; }
        public string CourierQty { get; set; }
    }
}
