//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyMaster
    {
        public CurrencyMaster()
        {
            this.POCurrExRates = new HashSet<POCurrExRate>();
            this.ServicePOMasters = new HashSet<ServicePOMaster>();
            this.StockPOMasters = new HashSet<StockPOMaster>();
            this.SupplierMasters = new HashSet<SupplierMaster>();
            this.LocationMasters = new HashSet<LocationMaster>();
        }
    
        public decimal CurrencyID { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> Ocur_ID { get; set; }
    
        public virtual ICollection<POCurrExRate> POCurrExRates { get; set; }
        public virtual ICollection<ServicePOMaster> ServicePOMasters { get; set; }
        public virtual ICollection<StockPOMaster> StockPOMasters { get; set; }
        public virtual ICollection<SupplierMaster> SupplierMasters { get; set; }
        public virtual ICollection<LocationMaster> LocationMasters { get; set; }
    }
}
