//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutOrderDO
    {
        public decimal CutOrderDO_PK { get; set; }
        public Nullable<decimal> DoDet_Pk { get; set; }
        public Nullable<decimal> CutID { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public Nullable<decimal> Skudet_PK { get; set; }
    
        public virtual CutOrderDO CutOrderDO1 { get; set; }
        public virtual CutOrderDO CutOrderDO2 { get; set; }
        public virtual CutOrderMaster CutOrderMaster { get; set; }
        public virtual DeliveryOrderDetail DeliveryOrderDetail { get; set; }
    }
}
