//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuttingDetail
    {
        public decimal CutID { get; set; }
        public string ATCNum { get; set; }
        public string Buyer { get; set; }
        public string Buyer_style { get; set; }
        public string Movex_style { get; set; }
        public string development { get; set; }
        public string Proto { get; set; }
        public string firstsample { get; set; }
        public string secondsample { get; set; }
        public string thirdsample { get; set; }
        public string sizeset { get; set; }
        public string styling { get; set; }
        public string mtl { get; set; }
        public string design { get; set; }
        public string costing { get; set; }
        public string booking { get; set; }
        public string Fabric_type { get; set; }
        public string width { get; set; }
        public string Description { get; set; }
        public string Merchandiser { get; set; }
        public string Designer { get; set; }
        public string original_sample { get; set; }
        public string spec { get; set; }
        public string style_diagram { get; set; }
        public string pattern { get; set; }
        public string size1 { get; set; }
        public string size2 { get; set; }
        public string size3 { get; set; }
        public string size4 { get; set; }
        public string qty1 { get; set; }
        public string qty2 { get; set; }
        public string qty3 { get; set; }
        public string qty4 { get; set; }
        public string Total { get; set; }
        public string PocketIn { get; set; }
        public string InterLinin { get; set; }
        public string MainLable { get; set; }
        public string CareLable { get; set; }
        public string SizeLable { get; set; }
        public string Joker { get; set; }
        public string TapeLable { get; set; }
        public string Thread { get; set; }
        public string Button { get; set; }
        public string Zippernick { get; set; }
        public string Lined { get; set; }
        public string Others { get; set; }
        public string ButtonHoles { get; set; }
        public string WashingInstruction { get; set; }
        public string master { get; set; }
    }
}
