//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryStockReceiptMaster
    {
        public DeliveryStockReceiptMaster()
        {
            this.DeliveryReceiptStockDetails = new HashSet<DeliveryReceiptStockDetail>();
        }
    
        public decimal SDOR_PK { get; set; }
        public string SDORNum { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public Nullable<decimal> SDO_PK { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string DOReceiptType { get; set; }
    
        public virtual DeliveryOrderStockMaster DeliveryOrderStockMaster { get; set; }
        public virtual ICollection<DeliveryReceiptStockDetail> DeliveryReceiptStockDetails { get; set; }
    }
}
