//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReceiptDetail
    {
        public decimal DORDet_Pk { get; set; }
        public Nullable<decimal> DOR_PK { get; set; }
        public Nullable<decimal> InventoryItem_PK { get; set; }
        public Nullable<decimal> DODet_PK { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
    
        public virtual DeliveryOrderDetail DeliveryOrderDetail { get; set; }
        public virtual DeliveryReceiptDetail DeliveryReceiptDetail1 { get; set; }
        public virtual DeliveryReceiptDetail DeliveryReceiptDetail2 { get; set; }
        public virtual DeliveryReceiptDetail DeliveryReceiptDetail11 { get; set; }
        public virtual DeliveryReceiptDetail DeliveryReceiptDetail3 { get; set; }
    }
}
