//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrderStockDetail
    {
        public DeliveryOrderStockDetail()
        {
            this.DeliveryReceiptStockDetails = new HashSet<DeliveryReceiptStockDetail>();
        }
    
        public decimal SDODet_PK { get; set; }
        public Nullable<decimal> SDO_PK { get; set; }
        public Nullable<decimal> SInventoryItem_PK { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public string Remark { get; set; }
    
        public virtual DeliveryOrderStockDetail DeliveryOrderStockDetails1 { get; set; }
        public virtual DeliveryOrderStockDetail DeliveryOrderStockDetail1 { get; set; }
        public virtual StockInventoryMaster StockInventoryMaster { get; set; }
        public virtual ICollection<DeliveryReceiptStockDetail> DeliveryReceiptStockDetails { get; set; }
    }
}
