//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReceiptStockDetail
    {
        public decimal SDORDet_Pk { get; set; }
        public Nullable<decimal> SDOR_PK { get; set; }
        public Nullable<decimal> SInventoryItem_PK { get; set; }
        public Nullable<decimal> SDODet_PK { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
    
        public virtual DeliveryOrderStockDetail DeliveryOrderStockDetail { get; set; }
        public virtual DeliveryStockReceiptMaster DeliveryStockReceiptMaster { get; set; }
        public virtual StockInventoryMaster StockInventoryMaster { get; set; }
    }
}
