//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraRequestReasonMaster
    {
        public ExtraRequestReasonMaster()
        {
            this.CutOrderMasters = new HashSet<CutOrderMaster>();
        }
    
        public decimal ExtraReason_Pk { get; set; }
        public string ExtraReason { get; set; }
    
        public virtual ICollection<CutOrderMaster> CutOrderMasters { get; set; }
    }
}
