//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactWareLinkMaster
    {
        public decimal FactWar_PK { get; set; }
        public Nullable<decimal> FromLoc_pk { get; set; }
        public Nullable<decimal> ToLoc_PK { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual LocationMaster LocationMaster1 { get; set; }
    }
}
