//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInTransit
    {
        public decimal Gt_PK { get; set; }
        public Nullable<decimal> InventoryItem_PK { get; set; }
        public Nullable<decimal> TransitQty { get; set; }
        public Nullable<decimal> DO_PK { get; set; }
    
        public virtual DeliveryOrderMaster DeliveryOrderMaster { get; set; }
        public virtual InventoryMaster InventoryMaster { get; set; }
    }
}
