//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMissingRequest
    {
        public InventoryMissingRequest()
        {
            this.InventoryMissingDetails = new HashSet<InventoryMissingDetail>();
        }
    
        public decimal MisplaceApp_pk { get; set; }
        public Nullable<decimal> FromLctn_pk { get; set; }
        public Nullable<decimal> Atc_id { get; set; }
        public decimal MisplaceDate { get; set; }
        public string Explanation { get; set; }
        public string AddedBy { get; set; }
        public string Addeddate { get; set; }
        public string Level1Approval { get; set; }
        public string Level1ApprovedBY { get; set; }
        public Nullable<decimal> IsApproved { get; set; }
        public Nullable<decimal> ApprovedBy { get; set; }
    
        public virtual ICollection<InventoryMissingDetail> InventoryMissingDetails { get; set; }
    }
}
