//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStockTransferDetail
    {
        public decimal GtransDet_Pk { get; set; }
        public Nullable<decimal> Gtrans_Pk { get; set; }
        public Nullable<decimal> FromSkudet_PK { get; set; }
        public Nullable<decimal> FromIIT_Pk { get; set; }
        public Nullable<decimal> Template_PK { get; set; }
        public Nullable<decimal> OldUnitrate { get; set; }
        public Nullable<decimal> NewUnitRate { get; set; }
        public decimal Qty { get; set; }
    
        public virtual InventoryStockTransferMaster InventoryStockTransferMaster { get; set; }
    }
}
