//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMissingDetail
    {
        public decimal MisplaceAppDet_PK { get; set; }
        public Nullable<decimal> MisplaceApp_PK { get; set; }
        public Nullable<decimal> InventoryItem_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Remark { get; set; }
    
        public virtual InventoryMissingRequest InventoryMissingRequest { get; set; }
    }
}
