//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMaster
    {
        public InventoryMaster()
        {
            this.DeliveryOrderDetails = new HashSet<DeliveryOrderDetail>();
            this.GoodsInTransits = new HashSet<GoodsInTransit>();
            this.TransferToGstockDetails = new HashSet<TransferToGstockDetail>();
        }
    
        public decimal InventoryItem_PK { get; set; }
        public Nullable<decimal> MrnDet_PK { get; set; }
        public Nullable<decimal> SkuDet_Pk { get; set; }
        public Nullable<decimal> PoDet_PK { get; set; }
        public Nullable<decimal> OnhandQty { get; set; }
        public string ReceivedVia { get; set; }
        public Nullable<decimal> Location_PK { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> DeliveredQty { get; set; }
        public string Refnum { get; set; }
        public Nullable<decimal> CURate { get; set; }
        public Nullable<decimal> Uom_Pk { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual ICollection<DeliveryOrderDetail> DeliveryOrderDetails { get; set; }
        public virtual ICollection<GoodsInTransit> GoodsInTransits { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual MrnDetail MrnDetail { get; set; }
        public virtual ProcurementDetail ProcurementDetail { get; set; }
        public virtual SkuRawmaterialDetail SkuRawmaterialDetail { get; set; }
        public virtual ICollection<TransferToGstockDetail> TransferToGstockDetails { get; set; }
    }
}
