//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobContractOptionalMaster
    {
        public JobContractOptionalMaster()
        {
            this.JobContractOptionalDetails = new HashSet<JobContractOptionalDetail>();
        }
    
        public decimal JobContractOptional_pk { get; set; }
        public string JobContractOptionalNUM { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public Nullable<decimal> AtcID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    
        public virtual AtcMaster AtcMaster { get; set; }
        public virtual ICollection<JobContractOptionalDetail> JobContractOptionalDetails { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
