//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobContractMaster
    {
        public JobContractMaster()
        {
            this.JobContractDetails = new HashSet<JobContractDetail>();
        }
    
        public decimal JobContract_pk { get; set; }
        public string JOBContractNUM { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public Nullable<decimal> AtcID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    
        public virtual AtcMaster AtcMaster { get; set; }
        public virtual ICollection<JobContractDetail> JobContractDetails { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
