//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobContractOptionalDetail
    {
        public decimal JobContractOptionalDetail_pk { get; set; }
        public Nullable<decimal> JobContractOptional_pk { get; set; }
        public Nullable<decimal> PoPackID { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public Nullable<decimal> Wash { get; set; }
        public Nullable<decimal> EmbroidaryPrinting { get; set; }
        public Nullable<decimal> CompanyLogistic { get; set; }
        public Nullable<decimal> FactoryLogistc { get; set; }
    
        public virtual AtcDetail AtcDetail { get; set; }
        public virtual JobContractOptionalMaster JobContractOptionalMaster { get; set; }
        public virtual PoPackMaster PoPackMaster { get; set; }
    }
}
