//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobContractDetail
    {
        public JobContractDetail()
        {
            this.ProductionReportDetails = new HashSet<ProductionReportDetail>();
            this.ShipmentHandOverDetails = new HashSet<ShipmentHandOverDetail>();
        }
    
        public decimal JobContractDetail_pk { get; set; }
        public Nullable<decimal> JobContract_pk { get; set; }
        public Nullable<decimal> PoPackID { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public Nullable<double> CMvalue { get; set; }
    
        public virtual AtcDetail AtcDetail { get; set; }
        public virtual JobContractMaster JobContractMaster { get; set; }
        public virtual PoPackMaster PoPackMaster { get; set; }
        public virtual ICollection<ProductionReportDetail> ProductionReportDetails { get; set; }
        public virtual ICollection<ShipmentHandOverDetail> ShipmentHandOverDetails { get; set; }
    }
}
