//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCDetail
    {
        public LCDetail()
        {
            this.LCBankAdviceDetails = new HashSet<LCBankAdviceDetail>();
        }
    
        public decimal LCDet_PK { get; set; }
        public string POType { get; set; }
        public string ATCnum { get; set; }
        public string PONUM { get; set; }
        public Nullable<decimal> PO_PK { get; set; }
        public Nullable<decimal> LCValue { get; set; }
        public string InvoiceNUM { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> LC_PK { get; set; }
    
        public virtual ICollection<LCBankAdviceDetail> LCBankAdviceDetails { get; set; }
        public virtual LCMaster LCMaster { get; set; }
    }
}
