//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCMaster
    {
        public LCMaster()
        {
            this.LCDetails = new HashSet<LCDetail>();
        }
    
        public decimal LC_PK { get; set; }
        public string LCNum { get; set; }
        public Nullable<decimal> Bank_PK { get; set; }
        public Nullable<System.DateTime> Issuedate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> Supplier_pk { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
        public virtual ICollection<LCDetail> LCDetails { get; set; }
        public virtual SupplierMaster SupplierMaster { get; set; }
    }
}
