//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTermMaster
    {
        public PaymentTermMaster()
        {
            this.StockPOMasters = new HashSet<StockPOMaster>();
        }
    
        public decimal PaymentTermID { get; set; }
        public string PaymentTermCode { get; set; }
        public string PaymentCodeDescription { get; set; }
    
        public virtual ICollection<StockPOMaster> StockPOMasters { get; set; }
    }
}
