//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentModeMaster
    {
        public decimal PaymentModeID { get; set; }
        public string PaymentModeCode { get; set; }
        public string PaymentModeDescription { get; set; }
    }
}
