//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class POApproval
    {
        public decimal POPending_PK { get; set; }
        public Nullable<decimal> PO_PK { get; set; }
        public string ForwardedBy { get; set; }
        public string IApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
