//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementDetail
    {
        public ProcurementDetail()
        {
            this.InventoryMasters = new HashSet<InventoryMaster>();
            this.MrnDetails = new HashSet<MrnDetail>();
            this.SupplierInvoiceDetails = new HashSet<SupplierInvoiceDetail>();
        }
    
        public decimal PODet_PK { get; set; }
        public Nullable<decimal> PO_Pk { get; set; }
        public Nullable<decimal> SkuDet_PK { get; set; }
        public Nullable<decimal> POQty { get; set; }
        public Nullable<decimal> POUnitRate { get; set; }
        public string SupplierSize { get; set; }
        public string SupplierColor { get; set; }
        public Nullable<decimal> Uom_PK { get; set; }
        public Nullable<decimal> CURate { get; set; }
    
        public virtual ICollection<InventoryMaster> InventoryMasters { get; set; }
        public virtual ICollection<MrnDetail> MrnDetails { get; set; }
        public virtual ProcurementMaster ProcurementMaster { get; set; }
        public virtual SkuRawmaterialDetail SkuRawmaterialDetail { get; set; }
        public virtual UOMMaster UOMMaster { get; set; }
        public virtual ICollection<SupplierInvoiceDetail> SupplierInvoiceDetails { get; set; }
    }
}
