//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecieptMaster
    {
        public RecieptMaster()
        {
            this.MrnMasters = new HashSet<MrnMaster>();
        }
    
        public decimal Reciept_Pk { get; set; }
        public string RecieptNum { get; set; }
        public Nullable<decimal> RecptLocation_PK { get; set; }
        public string ContainerNum { get; set; }
        public string BOENum { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> InhouseDate { get; set; }
        public Nullable<System.DateTime> Deliverydate { get; set; }
        public Nullable<decimal> Supplier_PK { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string IsCompleted { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<MrnMaster> MrnMasters { get; set; }
        public virtual SupplierMaster SupplierMaster { get; set; }
    }
}
