//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrderStockDetail
    {
        public decimal RODet_Pk { get; set; }
        public Nullable<decimal> SRO_Pk { get; set; }
        public Nullable<decimal> ToSkuDet_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> CUnitPrice { get; set; }
        public Nullable<decimal> SInventoryItem_PK { get; set; }
    
        public virtual RequestOrderStockMaster RequestOrderStockMaster { get; set; }
    }
}
