//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrderDetail
    {
        public RequestOrderDetail()
        {
            this.RoInDetails = new HashSet<RoInDetail>();
        }
    
        public decimal RODet_Pk { get; set; }
        public Nullable<decimal> RO_Pk { get; set; }
        public Nullable<decimal> FromSkuDet_PK { get; set; }
        public Nullable<decimal> ToSkuDet_PK { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<double> CUnitPrice { get; set; }
        public Nullable<decimal> InventoryItem_PK { get; set; }
    
        public virtual RequestOrderMaster RequestOrderMaster { get; set; }
        public virtual ICollection<RoInDetail> RoInDetails { get; set; }
    }
}
