//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoInDetail
    {
        public decimal RoInDet_PK { get; set; }
        public Nullable<decimal> ROIN_PK { get; set; }
        public Nullable<decimal> RODet_Pk { get; set; }
        public Nullable<decimal> FromSkuDet_PK { get; set; }
        public Nullable<decimal> ToSkuDet_Pk { get; set; }
        public Nullable<decimal> InventoryItem_PK { get; set; }
        public Nullable<decimal> RoQty { get; set; }
        public Nullable<decimal> CuRate { get; set; }
    
        public virtual RequestOrderDetail RequestOrderDetail { get; set; }
        public virtual ROINMaster ROINMaster { get; set; }
    }
}
