//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROINMaster
    {
        public ROINMaster()
        {
            this.RoInDetails = new HashSet<RoInDetail>();
        }
    
        public decimal ROIN_PK { get; set; }
        public Nullable<decimal> RO_Pk { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<decimal> Location_pk { get; set; }
        public string ROInNum { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual RequestOrderMaster RequestOrderMaster { get; set; }
        public virtual ICollection<RoInDetail> RoInDetails { get; set; }
    }
}
