//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RollInventoryMaster
    {
        public decimal RollInventory_PK { get; set; }
        public Nullable<decimal> Roll_PK { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public string DocumentNum { get; set; }
        public string AddedVia { get; set; }
        public string IsPresent { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> Addeddate { get; set; }
    
        public virtual FabricRollmaster FabricRollmaster { get; set; }
    }
}
