//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePOMaster
    {
        public decimal ServicePO_PK { get; set; }
        public string ServicePOnumber { get; set; }
        public string DebitFrom { get; set; }
        public string DebitName { get; set; }
        public Nullable<decimal> ServiceType_Pk { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CurrencyID { get; set; }
        public string Description { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string IsApproved { get; set; }
        public string IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual ServiceTypeMaster ServiceTypeMaster { get; set; }
    }
}
