//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTypeMaster
    {
        public ServiceTypeMaster()
        {
            this.ServicePOMasters = new HashSet<ServicePOMaster>();
        }
    
        public decimal ServiceType_Pk { get; set; }
        public string ServiceType { get; set; }
    
        public virtual ICollection<ServicePOMaster> ServicePOMasters { get; set; }
    }
}
