//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentHandOverMaster
    {
        public ShipmentHandOverMaster()
        {
            this.ShipmentHandOverDetails = new HashSet<ShipmentHandOverDetail>();
        }
    
        public decimal ShipmentHandMaster_PK { get; set; }
        public string ShipmentHandOverCode { get; set; }
        public string IsCompleted { get; set; }
        public decimal Location_Pk { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<ShipmentHandOverDetail> ShipmentHandOverDetails { get; set; }
    }
}
