//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuRawmaterialDetail
    {
        public SkuRawmaterialDetail()
        {
            this.CutOrderMasters = new HashSet<CutOrderMaster>();
            this.InventoryMasters = new HashSet<InventoryMaster>();
            this.MrnDetails = new HashSet<MrnDetail>();
            this.ProcurementDetails = new HashSet<ProcurementDetail>();
            this.TransferToGstockDetails = new HashSet<TransferToGstockDetail>();
        }
    
        public decimal SkuDet_PK { get; set; }
        public Nullable<decimal> Sku_PK { get; set; }
        public Nullable<decimal> SkuDet_id { get; set; }
        public string ColorCode { get; set; }
        public string SizeCode { get; set; }
        public string ItemColor { get; set; }
        public string SupplierColor { get; set; }
        public string ItemSize { get; set; }
        public string SupplierSize { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string RqdQty { get; set; }
        public string Dependency { get; set; }
        public string ColorName { get; set; }
        public string SizeName { get; set; }
    
        public virtual ICollection<CutOrderMaster> CutOrderMasters { get; set; }
        public virtual ICollection<InventoryMaster> InventoryMasters { get; set; }
        public virtual ICollection<MrnDetail> MrnDetails { get; set; }
        public virtual ICollection<ProcurementDetail> ProcurementDetails { get; set; }
        public virtual SkuRawMaterialMaster SkuRawMaterialMaster { get; set; }
        public virtual ICollection<TransferToGstockDetail> TransferToGstockDetails { get; set; }
    }
}
