//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInventoryMaster
    {
        public StockInventoryMaster()
        {
            this.DeliveryOrderStockDetails = new HashSet<DeliveryOrderStockDetail>();
            this.DeliveryReceiptStockDetails = new HashSet<DeliveryReceiptStockDetail>();
            this.StockGoodsInTransits = new HashSet<StockGoodsInTransit>();
        }
    
        public decimal SInventoryItem_PK { get; set; }
        public decimal SMRNDet_Pk { get; set; }
        public decimal SPODetails_PK { get; set; }
        public Nullable<decimal> Template_PK { get; set; }
        public string Composition { get; set; }
        public string Construct { get; set; }
        public string TemplateColor { get; set; }
        public string TemplateSize { get; set; }
        public string TemplateWidth { get; set; }
        public string TemplateWeight { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> OnHandQty { get; set; }
        public Nullable<decimal> Uom_PK { get; set; }
        public string ReceivedVia { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public string Refnum { get; set; }
        public Nullable<decimal> DeliveredQty { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual ICollection<DeliveryOrderStockDetail> DeliveryOrderStockDetails { get; set; }
        public virtual ICollection<DeliveryReceiptStockDetail> DeliveryReceiptStockDetails { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<StockGoodsInTransit> StockGoodsInTransits { get; set; }
        public virtual StockMRNDetail StockMRNDetail { get; set; }
        public virtual StockPODetail StockPODetail { get; set; }
        public virtual Template_Master Template_Master { get; set; }
    }
}
