//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMRNDetail
    {
        public StockMRNDetail()
        {
            this.StockInventoryMasters = new HashSet<StockInventoryMaster>();
        }
    
        public decimal SMRNDet_Pk { get; set; }
        public decimal SPODetails_PK { get; set; }
        public Nullable<decimal> SMRN_Pk { get; set; }
        public decimal SPO_PK { get; set; }
        public Nullable<decimal> Template_PK { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> Uom_PK { get; set; }
        public Nullable<decimal> ExtraQty { get; set; }
    
        public virtual ICollection<StockInventoryMaster> StockInventoryMasters { get; set; }
        public virtual StockPODetail StockPODetail { get; set; }
        public virtual StockPOMaster StockPOMaster { get; set; }
        public virtual Template_Master Template_Master { get; set; }
    }
}
