//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPODetail
    {
        public StockPODetail()
        {
            this.StockInventoryMasters = new HashSet<StockInventoryMaster>();
            this.StockMRNDetails = new HashSet<StockMRNDetail>();
        }
    
        public decimal SPODetails_PK { get; set; }
        public decimal SPO_PK { get; set; }
        public Nullable<decimal> Template_PK { get; set; }
        public string Composition { get; set; }
        public string Construct { get; set; }
        public string TemplateColor { get; set; }
        public string TemplateSize { get; set; }
        public string TemplateWidth { get; set; }
        public string TemplateWeight { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<decimal> POQty { get; set; }
        public Nullable<decimal> Uom_PK { get; set; }
    
        public virtual ICollection<StockInventoryMaster> StockInventoryMasters { get; set; }
        public virtual ICollection<StockMRNDetail> StockMRNDetails { get; set; }
        public virtual StockPOMaster StockPOMaster { get; set; }
    }
}
