//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMrnMaster
    {
        public decimal SMrn_PK { get; set; }
        public string SMrnNum { get; set; }
        public Nullable<decimal> SPo_PK { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Remark { get; set; }
        public string AddedBY { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string DoNumber { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public Nullable<decimal> SReciept_Pk { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual StockMrnMaster StockMrnMaster1 { get; set; }
        public virtual StockMrnMaster StockMrnMaster2 { get; set; }
        public virtual StockRecieptMaster StockRecieptMaster { get; set; }
    }
}
