//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleCostingMaster
    {
        public StyleCostingMaster()
        {
            this.StyleCostingComponentDetails = new HashSet<StyleCostingComponentDetail>();
            this.StyleCostingDetails = new HashSet<StyleCostingDetail>();
        }
    
        public decimal Costing_PK { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> MarginValue { get; set; }
        public Nullable<decimal> FOB { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> CostingCount { get; set; }
        public string IsApplicable { get; set; }
        public string IsSubmitted { get; set; }
        public string IsAccountable { get; set; }
        public string IsLast { get; set; }
    
        public virtual AtcDetail AtcDetail { get; set; }
        public virtual ICollection<StyleCostingComponentDetail> StyleCostingComponentDetails { get; set; }
        public virtual ICollection<StyleCostingDetail> StyleCostingDetails { get; set; }
    }
}
