//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleColor
    {
        public decimal StyleColorid { get; set; }
        public Nullable<decimal> AtcId { get; set; }
        public Nullable<decimal> OurStyleID { get; set; }
        public string GarmentColorCode { get; set; }
        public string GarmentColor { get; set; }
        public string OurStyle { get; set; }
    }
}
