//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleCostingComponentDetail
    {
        public decimal StyleCostingCom_Pk { get; set; }
        public Nullable<decimal> Costing_PK { get; set; }
        public Nullable<decimal> CostComp_PK { get; set; }
        public Nullable<decimal> CompValue { get; set; }
        public string CalculationMode { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    
        public virtual CostingComponentMaster CostingComponentMaster { get; set; }
        public virtual StyleCostingMaster StyleCostingMaster { get; set; }
    }
}
