//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleCostingDetail
    {
        public decimal CostingDetail_PK { get; set; }
        public Nullable<decimal> Costing_PK { get; set; }
        public Nullable<decimal> Sku_PK { get; set; }
        public Nullable<decimal> Consumption { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string IsRequired { get; set; }
        public Nullable<decimal> PriceperDozen { get; set; }
        public Nullable<decimal> Priceperpc { get; set; }
    
        public virtual SkuRawMaterialMaster SkuRawMaterialMaster { get; set; }
        public virtual StyleCostingMaster StyleCostingMaster { get; set; }
    }
}
