//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierUserMaster
    {
        public decimal SupplierUser_PK { get; set; }
        public string SUserName { get; set; }
        public string Spassword { get; set; }
        public Nullable<decimal> Supplier_PK { get; set; }
    }
}
