//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierStockInvoiceDetail
    {
        public decimal SupplierStockInvoiceDet_PK { get; set; }
        public Nullable<decimal> SupplierStockInvoice_PK { get; set; }
        public Nullable<decimal> SPODetails_PK { get; set; }
        public Nullable<decimal> InvoiceQty { get; set; }
        public Nullable<decimal> Unitrate { get; set; }
        public string InvCurrency { get; set; }
    
        public virtual SupplierStockInvoiceMaster SupplierStockInvoiceMaster { get; set; }
    }
}
