//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_Master
    {
        public Template_Master()
        {
            this.AtcRawMaterialMasters = new HashSet<AtcRawMaterialMaster>();
            this.StockInventoryMasters = new HashSet<StockInventoryMaster>();
            this.StockMRNDetails = new HashSet<StockMRNDetail>();
            this.TemplateColors = new HashSet<TemplateColor>();
            this.TemplateCompositions = new HashSet<TemplateComposition>();
            this.TemplateConstructions = new HashSet<TemplateConstruction>();
            this.TemplateSizes = new HashSet<TemplateSize>();
            this.TemplateWeights = new HashSet<TemplateWeight>();
            this.TemplateWidths = new HashSet<TemplateWidth>();
            this.TransferToGstockDetails = new HashSet<TransferToGstockDetail>();
        }
    
        public decimal Template_PK { get; set; }
        public string TemplateCode { get; set; }
        public string Description { get; set; }
        public decimal ItemGroup_PK { get; set; }
        public string HCCode { get; set; }
        public decimal Uom_PK { get; set; }
        public decimal Wastage { get; set; }
        public string IsItemColor { get; set; }
        public string IsItemSize { get; set; }
        public string IsStock { get; set; }
    
        public virtual ICollection<AtcRawMaterialMaster> AtcRawMaterialMasters { get; set; }
        public virtual ItemGroupMaster ItemGroupMaster { get; set; }
        public virtual ICollection<StockInventoryMaster> StockInventoryMasters { get; set; }
        public virtual ICollection<StockMRNDetail> StockMRNDetails { get; set; }
        public virtual UOMMaster UOMMaster { get; set; }
        public virtual ICollection<TemplateColor> TemplateColors { get; set; }
        public virtual ICollection<TemplateComposition> TemplateCompositions { get; set; }
        public virtual ICollection<TemplateConstruction> TemplateConstructions { get; set; }
        public virtual ICollection<TemplateSize> TemplateSizes { get; set; }
        public virtual ICollection<TemplateWeight> TemplateWeights { get; set; }
        public virtual ICollection<TemplateWidth> TemplateWidths { get; set; }
        public virtual ICollection<TransferToGstockDetail> TransferToGstockDetails { get; set; }
    }
}
