//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferToGstockMaster
    {
        public TransferToGstockMaster()
        {
            this.TransferToGstockDetails = new HashSet<TransferToGstockDetail>();
        }
    
        public decimal TransferToGSTock_PK { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IsDeleted { get; set; }
        public string AddedBy { get; set; }
        public string DeletedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> Approveddate { get; set; }
        public Nullable<decimal> Location_Pk { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string IsApproved { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<TransferToGstockDetail> TransferToGstockDetails { get; set; }
    }
}
