//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferToGstockDetail
    {
        public decimal TransferToGSTockDetail_PK { get; set; }
        public Nullable<decimal> TransferToGSTock_PK { get; set; }
        public Nullable<decimal> InventoryItemPK { get; set; }
        public Nullable<decimal> FromSkudet_PK { get; set; }
        public Nullable<decimal> Template_PK { get; set; }
        public Nullable<decimal> OldUnitprice { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> NewUnitprice { get; set; }
    
        public virtual InventoryMaster InventoryMaster { get; set; }
        public virtual SkuRawmaterialDetail SkuRawmaterialDetail { get; set; }
        public virtual Template_Master Template_Master { get; set; }
        public virtual TransferToGstockMaster TransferToGstockMaster { get; set; }
    }
}
