#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipit
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Art")]
	public partial class ArtDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAtcMaster(AtcMaster instance);
    partial void UpdateAtcMaster(AtcMaster instance);
    partial void DeleteAtcMaster(AtcMaster instance);
    #endregion
		
		public ArtDataDataContext() : 
				base(global::Shipit.Properties.Settings.Default.ArtConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ArtDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArtDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArtDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArtDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AtcMaster> AtcMasters
		{
			get
			{
				return this.GetTable<AtcMaster>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AtcMaster")]
	public partial class AtcMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _AtcId;
		
		private string _AtcNum;
		
		private decimal _Buyer_ID;
		
		private System.Nullable<decimal> _Country_ID;
		
		private string _MerchandiserName;
		
		private System.Nullable<decimal> _NoofStyles;
		
		private System.Nullable<System.DateTime> _HouseDate;
		
		private System.Nullable<System.DateTime> _ShipDate;
		
		private System.Nullable<System.DateTime> _FinishDate;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedDate;
		
		private string _IsCompleted;
		
		private string _IsClosed;
		
		private string _SeasonName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAtcIdChanging(decimal value);
    partial void OnAtcIdChanged();
    partial void OnAtcNumChanging(string value);
    partial void OnAtcNumChanged();
    partial void OnBuyer_IDChanging(decimal value);
    partial void OnBuyer_IDChanged();
    partial void OnCountry_IDChanging(System.Nullable<decimal> value);
    partial void OnCountry_IDChanged();
    partial void OnMerchandiserNameChanging(string value);
    partial void OnMerchandiserNameChanged();
    partial void OnNoofStylesChanging(System.Nullable<decimal> value);
    partial void OnNoofStylesChanged();
    partial void OnHouseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHouseDateChanged();
    partial void OnShipDateChanging(System.Nullable<System.DateTime> value);
    partial void OnShipDateChanged();
    partial void OnFinishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishDateChanged();
    partial void OnAddedByChanging(string value);
    partial void OnAddedByChanged();
    partial void OnAddedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAddedDateChanged();
    partial void OnIsCompletedChanging(string value);
    partial void OnIsCompletedChanged();
    partial void OnIsClosedChanging(string value);
    partial void OnIsClosedChanged();
    partial void OnSeasonNameChanging(string value);
    partial void OnSeasonNameChanged();
    #endregion
		
		public AtcMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtcId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal AtcId
		{
			get
			{
				return this._AtcId;
			}
			set
			{
				if ((this._AtcId != value))
				{
					this.OnAtcIdChanging(value);
					this.SendPropertyChanging();
					this._AtcId = value;
					this.SendPropertyChanged("AtcId");
					this.OnAtcIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtcNum", DbType="NVarChar(10)")]
		public string AtcNum
		{
			get
			{
				return this._AtcNum;
			}
			set
			{
				if ((this._AtcNum != value))
				{
					this.OnAtcNumChanging(value);
					this.SendPropertyChanging();
					this._AtcNum = value;
					this.SendPropertyChanged("AtcNum");
					this.OnAtcNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buyer_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal Buyer_ID
		{
			get
			{
				return this._Buyer_ID;
			}
			set
			{
				if ((this._Buyer_ID != value))
				{
					this.OnBuyer_IDChanging(value);
					this.SendPropertyChanging();
					this._Buyer_ID = value;
					this.SendPropertyChanged("Buyer_ID");
					this.OnBuyer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_ID", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> Country_ID
		{
			get
			{
				return this._Country_ID;
			}
			set
			{
				if ((this._Country_ID != value))
				{
					this.OnCountry_IDChanging(value);
					this.SendPropertyChanging();
					this._Country_ID = value;
					this.SendPropertyChanged("Country_ID");
					this.OnCountry_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerchandiserName", DbType="NVarChar(50)")]
		public string MerchandiserName
		{
			get
			{
				return this._MerchandiserName;
			}
			set
			{
				if ((this._MerchandiserName != value))
				{
					this.OnMerchandiserNameChanging(value);
					this.SendPropertyChanging();
					this._MerchandiserName = value;
					this.SendPropertyChanged("MerchandiserName");
					this.OnMerchandiserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoofStyles", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> NoofStyles
		{
			get
			{
				return this._NoofStyles;
			}
			set
			{
				if ((this._NoofStyles != value))
				{
					this.OnNoofStylesChanging(value);
					this.SendPropertyChanging();
					this._NoofStyles = value;
					this.SendPropertyChanged("NoofStyles");
					this.OnNoofStylesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> HouseDate
		{
			get
			{
				return this._HouseDate;
			}
			set
			{
				if ((this._HouseDate != value))
				{
					this.OnHouseDateChanging(value);
					this.SendPropertyChanging();
					this._HouseDate = value;
					this.SendPropertyChanged("HouseDate");
					this.OnHouseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShipDate
		{
			get
			{
				return this._ShipDate;
			}
			set
			{
				if ((this._ShipDate != value))
				{
					this.OnShipDateChanging(value);
					this.SendPropertyChanging();
					this._ShipDate = value;
					this.SendPropertyChanged("ShipDate");
					this.OnShipDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishDate
		{
			get
			{
				return this._FinishDate;
			}
			set
			{
				if ((this._FinishDate != value))
				{
					this.OnFinishDateChanging(value);
					this.SendPropertyChanging();
					this._FinishDate = value;
					this.SendPropertyChanged("FinishDate");
					this.OnFinishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="VarChar(20)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this.OnAddedByChanging(value);
					this.SendPropertyChanging();
					this._AddedBy = value;
					this.SendPropertyChanged("AddedBy");
					this.OnAddedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedDate
		{
			get
			{
				return this._AddedDate;
			}
			set
			{
				if ((this._AddedDate != value))
				{
					this.OnAddedDateChanging(value);
					this.SendPropertyChanging();
					this._AddedDate = value;
					this.SendPropertyChanged("AddedDate");
					this.OnAddedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCompleted", DbType="NChar(10)")]
		public string IsCompleted
		{
			get
			{
				return this._IsCompleted;
			}
			set
			{
				if ((this._IsCompleted != value))
				{
					this.OnIsCompletedChanging(value);
					this.SendPropertyChanging();
					this._IsCompleted = value;
					this.SendPropertyChanged("IsCompleted");
					this.OnIsCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsClosed", DbType="NChar(10)")]
		public string IsClosed
		{
			get
			{
				return this._IsClosed;
			}
			set
			{
				if ((this._IsClosed != value))
				{
					this.OnIsClosedChanging(value);
					this.SendPropertyChanging();
					this._IsClosed = value;
					this.SendPropertyChanged("IsClosed");
					this.OnIsClosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonName", DbType="NVarChar(50)")]
		public string SeasonName
		{
			get
			{
				return this._SeasonName;
			}
			set
			{
				if ((this._SeasonName != value))
				{
					this.OnSeasonNameChanging(value);
					this.SendPropertyChanging();
					this._SeasonName = value;
					this.SendPropertyChanged("SeasonName");
					this.OnSeasonNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
